### ISSUE TITLE
Podłączenie bazy danych

### ISSUE THREAD

**Issue by Kuba957** [Dyzio18/office-management-system#10]
Wykonać test działania bazy danych

**Comment by FishaPL** [comment]
Podłącznie do bazy danych na serwerze dalej nie działa. Poniżej moje próby/pomysły

+  Zamiana mysql12.mydevil.net == 31.186.81.74
+  ?autoReconnect=true&useSSL=false
+  ?verifyServerCertificate=false&useSSL=true
+  ?useUnicode=yes&characterEncoding=UTF-8&useSSL=false

+  dbConnection = DriverManager.getConnection(connectionString, Configs.dbuser.trim(), Configs.dbpassword.trim());//
-   Zmiana portu?
+  Użycie starszej wersji mysql-connectora
-   Dodanie nowego użytkownika do bazy danych
+  wyłączanie firewall

-   Please update your IP address in /etc/mysql/my.cnf file
     bind-address  = <IP_ADDRESS>
     Restart mysql deamon and mysql services.

-   Connection connection = DriverManager.getConnection("jdbc:mysql://localhost/?user=root&password=rootpassword");
     PreparedStatement ps = connection.prepareStatement("CREATE DATABASE databasename");
     int result = ps.executeUpdate();
